#
# Copyright (c) 2021 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# System
CONFIG_THREAD_NAME=y
CONFIG_MPU_STACK_GUARD=y
CONFIG_RESET_ON_FATAL_ERROR=n
CONFIG_USE_SEGGER_RTT=n
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

# pH sensor — Serial + On-Demand
CONFIG_SENSOR=y
CONFIG_I2C=y
CONFIG_PH_SENSOR=y
CONFIG_PH_SENSOR_TRANSPORT_SERIAL=y
CONFIG_PH_SENSOR_MODE_ON_DEMAND=y
CONFIG_PH_SENSOR_I2C_READ_TIMEOUT_MS=2000
